# Generated by Django 4.0.3 on 2022-08-31 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b10f6b57-f233-46d9-93c3-332a23cc0e13'), editable=False, primary_key=True, serialize=False),
        ),
    ]
