# Generated by Django 4.0.3 on 2022-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_code_alter_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='code',
            field=models.CharField(default='6f271dbfc79a4dc1958cf9a2f1e41f01', editable=False, max_length=255, unique=True),
        ),
    ]
