# Generated by Django 4.0.3 on 2022-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='photo',
            field=models.ImageField(upload_to='static/meet'),
        ),
    ]
