# Generated by Django 4.0.3 on 2022-08-30 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_meet_description_alter_meet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to=settings.AUTH_USER_MODEL),
        ),
    ]
